### ISSUE TITLE
闪退了。。。

### ISSUE THREAD

**Issue by cyqluowang** [zzhoujay/RichText#105]
java.lang.IllegalArgumentException: unexpected url: file://C:/Users/dhx/Documents/Tencent Files/3260035923/Image/Group/Image2/N`CJFCEE`Y~R7[3C4L[WL`V.jpg
                                                                   at okhttp3.Request$Builder.url(Request.java:142)
                                                                   at com.zzhoujay.richtext.ig.DefaultImageGetter.getDrawable(DefaultImageGetter.java:144)
                                                                   at com.zzhoujay.richtext.RichText.getDrawable(RichText.java:342)
                                                                   at com.zzhoujay.richtext.parser.CachedSpannedParser.handleImage(CachedSpannedParser.java:119)
                                                                   at com.zzhoujay.richtext.parser.CachedSpannedParser.parse(CachedSpannedParser.java:33)
                                                                   at com.zzhoujay.richtext.RichText.generateRichText(RichText.java:179)
                                                                   at com.zzhoujay.richtext.RichText.access$000(RichText.java:39)
                                                                   at com.zzhoujay.richtext.RichText$1.run(RichText.java:149)
                                                                   at android.os.Handler.handleCallback(Handler.java:815)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                   at android.os.Looper.loop(Looper.java:194)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5838)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1009)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)

**Comment by cyqluowang** [comment]
如果图片地址有问题的话

**Comment by zzhoujay** [comment]
目前DefaultImageGetter暂时不支持加载本地文件，下个版本会加入此功能，到时候再通知你

**Comment by zzhoujay** [comment]
现在可以用GlideImageGetter暂时替代下

**Comment by cyqluowang** [comment]
不支持的话我try不住，闪退不能解决。。。

**Comment by zzhoujay** [comment]
嗯，是之前的疏忽，后面会修复

**Comment by zzhoujay** [comment]
`2.4.0`版本里DefaultImageGetter增加了对本地图片的支持
