### ISSUE TITLE
No virtual method setImageWidth(I)V in class Lcom/zzhoujay/richtext/ImageHolder; or its super classes (declaration of 

### ISSUE THREAD

**Issue by micookie** [zzhoujay/RichText#118]
03-03 17:53:44.138 31531-31531/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: cxxxxxx, PID: 31531
                                                   java.lang.NoSuchMethodError: No virtual method setImageWidth(I)V in class Lcom/zzhoujay/richtext/ImageHolder; or its super classes (declaration of 'com.zzhoujay.richtext.ImageHolder' appears in /data/data/xxxxxxx/files/instant-run/dex/slice-com.zzhoujay.richtext-richtext-2.4.0_abebf3eb05a0c15f7e59cb95c9f789661dfb0c77-classes.dex)
                                                       at com.zzhoujay.glideimagegetter.ImageTargetBitmap.onResourceReady(ImageTargetBitmap.java:42)
                                                       at com.zzhoujay.glideimagegetter.ImageTargetBitmap.onResourceReady(ImageTargetBitmap.java:19)
                                                       at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:525)
                                                       at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:507)
                                                       at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:158)
                                                       at com.bumptech.glide.load.engine.EngineJob.access$100(EngineJob.java:22)
                                                       at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:202)
                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6095)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

应该是要把'com.zzhoujay.glideimagegetter:glideimagegetter:1.0.1'也更新一下
ImageHolder 里边方法名称改了

    public void setWidth(int width) {
        this.width = width;
    }

    public void setHeight(int height) {
        this.height = height;
    }

**Comment by micookie** [comment]
应该是要把'com.zzhoujay.glideimagegetter:glideimagegetter:1.0.1'也更新一下

**Comment by zzhoujay** [comment]
嗯，这个包忘更新了，不过现在默认的图片加载器已经可以解析gif图片和本地图片了，如果没有其他别的需求可以直接用默认图片加载器了

**Comment by zzhoujay** [comment]
已经修复了
