### ISSUE TITLE
多次刷新出现java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by lzy6** [zzhoujay/RichText#122]
这个是什么原因呢，有的多刷新几次就回出现这个错误，并不是所有页面都是

**Comment by zzhoujay** [comment]
麻烦把完整的错误栈发下

**Comment by lzy6** [comment]
java.util.ConcurrentModificationException
                                                     at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
                                                     at java.util.HashMap$KeyIterator.next(HashMap.java:814)
                                                     at com.zzhoujay.richtext.ig.DefaultImageGetter.checkTarget(DefaultImageGetter.java:108)
                                                     at com.zzhoujay.richtext.ig.DefaultImageGetter.getDrawable(DefaultImageGetter.java:146)
                                                     at com.zzhoujay.richtext.RichText.getDrawable(RichText.java:342)
                                                     at com.zzhoujay.richtext.parser.CachedSpannedParser.handleImage(CachedSpannedParser.java:119)
                                                     at com.zzhoujay.richtext.parser.CachedSpannedParser.parse(CachedSpannedParser.java:33)
                                                     at com.zzhoujay.richtext.RichText.generateRichText(RichText.java:179)
                                                     at com.zzhoujay.richtext.RichText.access$000(RichText.java:39)
                                                     at com.zzhoujay.richtext.RichText$1.run(RichText.java:149)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5359)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:919)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:714)

**Comment by lzy6** [comment]
机型是vivo v3maxA    5.1.1 
三星s7 没有出现这个bug

**Comment by lzy6** [comment]
<p><strong><span style=";font-family:宋体">发病症状</span></strong></p><p><span 

style="font-size:14px;font-family:'微软雅黑','sans-serif';color:#333333;background:white">叶缘、叶

尖变黄干枯，破裂，最后脱落。果梗、茎蔓及叶柄上病斑为水浸状不规则条斑，以后边缘暗褐色，中间灰白色隆起，

纵裂，呈疮痂状。果实上的病斑为暗褐色隆起的小点，后期木栓化，或呈泡疹状，逐渐扩大为黑色疮痂，潮湿时，疮

痂中间有菌液溢出。</span></p><p style="text-align: center;"><img 

src="http://cddupload.laoodao.cn/ueditor/image/20170228/1488262197904862.png" 

title="1488262185949125.png" alt="blob.png" /></p><p><strong><span style=";font-family:宋体">发生

规律</span></strong></p><p style="text-indent: 28px"><span style=";font-family:'微软雅黑','sans-

serif';color:#333333;background:white">在幼苗子叶中养分快耗尽而新根尚未扎实之前，由于营养供应紧张，造

成抗病力减弱，如果此时遇寒流或连续低温阴雨（雪）天气，而苗床保温不好，会突发此病。</span></p><p 

style="text-align: center;"><img 

src="http://cddupload.laoodao.cn/ueditor/image/20170228/1488262198236886.png" 

title="1488262198236886.png" alt="blob.png" /></p><p><strong><span style=";font-family:宋体">防治

方法</span></strong></p><p><span style=";font-family: '微软雅黑','sans-

serif';color:#333333;background:white">【栽培管理】</span></p><p style="text-indent: 28px"><span 

style=";font-family:'微软雅黑','sans-serif';color:#333333;background:white">该病的防治应以农业措施

为主，与非茄科作物实行2-3年轮作；苗床应选择地势高、避风向阳、排灌方便、土壤肥沃、透气性好的无病地块。为

防止苗床带入病菌，应施用腐熟的农家肥。</span></p><p><span style=";font-family: '微软雅黑','sans-

serif';color:#333333;background:white">【种子处理】</span></p><p style="text-indent: 28px"><span 

style=";font-family:'微软雅黑','sans-serif';color:#333333;background:white">用53％精甲霜·锰锌水分

散粒剂600-800倍液或72.2％霜霉威水剂800-1000倍液浸种。</span></p><p><span style=";font-family: '微软

雅黑','sans-serif';color:#333333;background:white">【药剂防治】</span></p><p style="text-indent: 

28px"><span style=";font-family:'微软雅黑','sans-serif';color:#333333;background:white">72.2％霜霉

威水剂400倍液＋70％代森锰锌可湿性粉剂600-1000倍液；53％精甲霜·锰锌可湿性粉剂600-800倍液；对水均匀喷雾

，视病情隔7-10天喷1次。</span></p><p><span style=";font-family:'微软雅黑','sans-

serif';color:#333333;background:white">&nbsp;</span></p>



我用的这个数据，用其他的数据还没发现这个问题

**Comment by zzhoujay** [comment]
你试试`2.4.1`版本还有问题没

**Comment by lzy6** [comment]
还是有的

**Comment by zzhoujay** [comment]
多刷新几次是什么意思？

**Comment by zzhoujay** [comment]
我这边用你的数据也测试不出问题来

**Comment by zzhoujay** [comment]
只在vivo v3maxA 5.1.1和这段文本才出现问题么？

**Comment by lzy6** [comment]
有的其他机型 6.0以下版本 也会有这个问题
多刷新就是前几次加载数据的时候没问题，但是多加载几次（下拉刷新）就会出这个问题

**Comment by lzy6** [comment]
你好，使用GlideImageGetter貌似就不会出现这个问题了，使用DefaultImageGetter就有

**Comment by zzhoujay** [comment]
那可以先用GlideIimageGetter我这边一直无法重现你说的bug，而且DefaultImageGetter和GlideIimageGetter主要区别只是图片下载的方式不同，具体的各种逻辑都是一致的，理论上要是有问题两边都应该有问题才对。
