### ISSUE TITLE
两个图片始终显示不出来，也没有占位符

### ISSUE THREAD

**Issue by zhengfei** [zzhoujay/RichText#150]
**html内容**：
```
<img src='http://cuncxforum-10008003.image.myqcloud.com/642def77-373f-434f-8e68-42dedbd9f880'/><br><img src='http://cuncxforum-10008003.image.myqcloud.com/bf153d9f-e8c3-4dcc-a23e-bfe0358cb429'/>
```
**调用方式**
```
RichText.from(comments.Content).size((int)(200* CCXUtil.getDensity(context)), ImageHolder.WRAP_CONTENT).error(R.drawable.msg_image_load_fail).placeHolder(R.drawable.msg_default_image).into(holder.content);
```

**控制台日志**
```
17:17:30.699 5860-5860/com.cuncx E/aaaaaa: comments.Content is <img src='http://cuncxforum-10008003.image.myqcloud.com/642def77-373f-434f-8e68-42dedbd9f880'/><br><img src='http://cuncxforum-10008003.image.myqcloud.com/bf153d9f-e8c3-4dcc-a23e-bfe0358cb429'/>
05-09 17:17:30.727 5860-5860/com.cuncx D/AbstractImageLoader: gg
05-09 17:17:30.727 5860-5860/com.cuncx D/AbstractImageLoader: gg
05-09 17:17:30.729 5860-5860/com.cuncx D/AbstractImageLoader: gg
05-09 17:17:30.729 5860-5860/com.cuncx D/AbstractImageLoader: gg
05-09 17:17:30.731 4305-4507/? I/XiaomiFirewall: firewall pkgName:com.cuncx, result:0x0
05-09 17:17:30.952 1925-2012/? I/WindowManager: Destroying surface Surface(name=com.cuncx/com.cuncx.ui.AFDetailActivity_) called by com.android.server.wm.WindowStateAnimator.destroySurface:2027 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:894 com.android.server.wm.WindowState.destroyOrSaveSurface:2074 com.android.server.wm.AppWindowToken.destroySurfaces:363 com.android.server.wm.WindowStateAnimator.finishExit:565 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:491 com.android.server.wm.WindowAnimator.updateWindowsLocked:306 com.android.server.wm.WindowAnimator.animateLocked:707 
05-09 17:17:30.962 1925-2012/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{bff57aa u0 com.cuncx/.ui.AFDetailActivity_ t179} time:110006057
05-09 17:17:30.986 1925-2012/? I/Timeline: Timeline: App_transition_stopped time:110006081
05-09 17:17:30.991 563-3506/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
05-09 17:17:30.991 563-3506/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
05-09 17:17:30.992 563-3506/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
05-09 17:17:30.992 563-3506/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
05-09 17:17:30.992 563-3506/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
05-09 17:17:30.992 563-3506/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
05-09 17:17:30.992 563-3506/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
05-09 17:17:30.993 563-3506/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
05-09 17:17:30.993 563-3506/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
05-09 17:17:30.993 563-3506/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
05-09 17:17:30.993 563-3506/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
05-09 17:17:30.994 563-3506/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
05-09 17:17:30.994 563-3506/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
05-09 17:17:30.994 563-3506/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
05-09 17:17:30.995 563-3506/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
05-09 17:17:30.995 563-3506/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
05-09 17:17:30.996 563-3506/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
05-09 17:17:30.997 563-3506/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
05-09 17:17:30.997 563-3506/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
05-09 17:17:30.998 563-3506/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
05-09 17:17:30.999 563-3506/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
05-09 17:17:31.000 563-3506/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
05-09 17:17:31.078 5860-7353/com.cuncx D/AbstractImageLoader: gg
05-09 17:17:31.122 5860-7351/com.cuncx D/AbstractImageLoader: gg
05-09 17:17:31.272 1925-3736/? D/ActivityTrigger: ActivityTrigger activityStopTrigger 
05-09 17:17:31.303 1925-25316/? I/WindowManager: Destroying surface Surface(name=com.cuncx/com.cuncx.ui.OrderDetailActivity_) called by com.android.server.wm.WindowStateAnimator.destroySurface:2027 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:894 com.android.server.wm.WindowState.destroyOrSaveSurface:2074 com.android.server.wm.WindowManagerService.tryStartExitingAnimation:3033 com.android.server.wm.WindowManagerService.relayoutWindow:2913 com.android.server.wm.Session.relayout:215 android.view.IWindowSession$Stub.onTransact:286 com.android.server.wm.Session.onTransact:136 
05-09 17:17:31.418 6217-6463/? W/System.err: java.net.SocketTimeoutException: connect timed out
05-09 17:17:31.430 6217-6463/? W/System.err:     at java.net.PlainSocketImpl.socketConnect(Native Method)
05-09 17:17:31.430 6217-6463/? W/System.err:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
05-09 17:17:31.430 6217-6463/? W/System.err:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
05-09 17:17:31.431 6217-6463/? W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
05-09 17:17:31.431 6217-6463/? W/System.err:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
05-09 17:17:31.431 6217-6463/? W/System.err:     at java.net.Socket.connect(Socket.java:586)
05-09 17:17:31.431 6217-6463/? W/System.err:     at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
05-09 17:17:31.431 6217-6463/? W/System.err:     at com.android.okhttp.Connection.connectSocket(Connection.java:196)
05-09 17:17:31.431 6217-6463/? W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:172)
05-09 17:17:31.432 6217-6463/? W/System.err:     at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
05-09 17:17:31.432 6217-6463/? W/System.err:     at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
05-09 17:17:31.432 6217-6463/? W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
05-09 17:17:31.432 6217-6463/? W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:247)
05-09 17:17:31.432 6217-6463/? W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
05-09 17:17:31.433 6217-6463/? W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
05-09 17:17:31.433 6217-6463/? W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
05-09 17:17:31.433 6217-6463/? W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
05-09 17:17:31.434 6217-6463/? W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
05-09 17:17:31.434 6217-6463/? W/System.err:     at com.ss.android.linkselector.d.b$b.a(SourceFile:108)
05-09 17:17:31.434 6217-6463/? W/System.err:     at com.ss.android.linkselector.d.b$b.run(SourceFile:81)
05-09 17:17:31.434 6217-6463/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-09 17:17:31.434 6217-6463/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-09 17:17:31.434 6217-6463/? W/System.err:     at java.lang.Thread.run(Thread.java:761)
```

**Comment by zhengfei** [comment]
我看日志里头有一个 W/System.err: java.net.SocketTimeoutException: connect timed out，但网络是好的，是不是超时时间设置的太短的缘故呢

**Comment by zzhoujay** [comment]
有没有用别的设备测试过？我在API17 的模拟器里使用下面的代码加载时没有问题的
```
private final String issue150 = "<img src='http://cuncxforum-10008003.image.myqcloud.com/642def77-373f-434f-8e68-42dedbd9f880'/><br><img src='http://cuncxforum-10008003.image.myqcloud.com/bf153d9f-e8c3-4dcc-a23e-bfe0358cb429'/>";


RichText.from(issue150).into(textView);
```

下个版本会增加设置超时时间的接口

**Comment by zhengfei** [comment]
我身边的两个机子，一个是小米4c，android7.0，一个是华为mate7 android6.0，都显示不出来

**Comment by zzhoujay** [comment]
网络问题？看上去就是超时的问题，okhttp默认超时时间好像是10秒钟的样子，10秒钟一张图片应该是可以加载才对啊，你在你的测试机上用浏览器访问图片的url看加载速度咋样
