### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by GongZiZhang** [zzhoujay/RichText#155]
at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
                                                                at java.util.HashMap$KeyIterator.next(HashMap.java:814)
                                                                at com.zzhoujay.richtext.ig.DefaultImageGetter.checkTarget(DefaultImageGetter.java:72)
                                                                at com.zzhoujay.richtext.ig.DefaultImageGetter.getDrawable(DefaultImageGetter.java:143)
                                                                at com.zzhoujay.richtext.RichText.getDrawable(RichText.java:336)
                                                                at com.zzhoujay.richtext.parser.CachedSpannedParser.handleImage(CachedSpannedParser.java:120)
                                                                at com.zzhoujay.richtext.parser.CachedSpannedParser.parse(CachedSpannedParser.java:34)
                                                                at com.zzhoujay.richtext.RichText.generateRichText(RichText.java:180)
                                                                at com.zzhoujay.richtext.RichText.access$000(RichText.java:37)
                                                                at com.zzhoujay.richtext.RichText$1.run(RichText.java:147)
                                                                at android.os.Handler.handleCallback(Handler.java:815)
                                                                at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                at android.os.Looper.loop(Looper.java:194)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5848)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
在快速滑动Recyclerview的时候，有时会出现这个问题

**Comment by zzhoujay** [comment]
抛出的异常名叫什么名？

**Comment by zzhoujay** [comment]
在`3.0.0`版本已解决这个问题
