### ISSUE TITLE
android 7.1运行报错

### ISSUE THREAD

**Issue by andyNinty** [zzhoujay/RichText#160]
`06-01 01:46:24.881 15744-15744/zhou.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                           Process: zhou.demo, PID: 15744
                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference
                                                               at com.zzhoujay.richtext.ext.MD5.generate(MD5.java:16)
                                                               at com.zzhoujay.richtext.RichTextPool.loadCache(RichTextPool.java:41)
                                                               at com.zzhoujay.richtext.RichText.generateRichText(RichText.java:173)
                                                               at com.zzhoujay.richtext.RichText.access$000(RichText.java:37)
                                                               at com.zzhoujay.richtext.RichText$1.run(RichText.java:147)
                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at android.os.Looper.loop(Looper.java:154)
                                                               at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by zzhoujay** [comment]
抱歉，最近没怎么看github，应该是source为null导致的吧
