### ISSUE TITLE
发现一个oom问题

### ISSUE THREAD

**Issue by GongZiZhang** [zzhoujay/RichText#204]
java.lang.OutOfMemoryError
                                                                  at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
                                                                  at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:623)
                                                                  at com.zzhoujay.richtext.ig.SourceDecode$3.decodeAsBitmap(SourceDecode.java:103)
                                                                  at com.zzhoujay.richtext.ig.SourceDecode$3.decodeAsBitmap(SourceDecode.java:67)
                                                                  at com.zzhoujay.richtext.ig.SourceDecode.decode(SourceDecode.java:130)
                                                                  at com.zzhoujay.richtext.ig.CallbackImageLoader.onResponse(CallbackImageLoader.java:49)
                                                                  at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
                                                                  at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                  at java.lang.Thread.run(Thread.java:841)

**Comment by ff-frida** [comment]
怎么重现这个问题呢？
