### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by coolhades** [zzhoujay/RichText#217]
报错：
java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                     at android.os.AsyncTask$3.done(AsyncTask.java:318)
                                                     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                     at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                     at java.lang.Thread.run(Thread.java:761)
                                                  Caused by: java.util.ConcurrentModificationException
                                                     at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
                                                     at java.util.HashMap$KeyIterator.next(HashMap.java:885)
                                                     at com.zzhoujay.richtext.ig.DefaultImageGetter.checkTarget(DefaultImageGetter.java:72)
                                                     at com.zzhoujay.richtext.ig.DefaultImageGetter.getDrawable(DefaultImageGetter.java:149)
                                                     at com.zzhoujay.richtext.RichText.getDrawable(RichText.java:378)
                                                     at com.zzhoujay.richtext.parser.CachedSpannedParser.handleImage(CachedSpannedParser.java:120)
                                                     at com.zzhoujay.richtext.parser.CachedSpannedParser.parse(CachedSpannedParser.java:34)
                                                     at com.zzhoujay.richtext.RichText.generateRichText(RichText.java:222)
                                                     at com.zzhoujay.richtext.RichText.access$100(RichText.java:39)
                                                     at com.zzhoujay.richtext.RichText$2.doInBackground(RichText.java:168)
                                                     at com.zzhoujay.richtext.RichText$2.doInBackground(RichText.java:156)
                                                     at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                     at java.lang.Thread.run(Thread.java:761)

**Comment by zzhoujay** [comment]
试试`3.0.2`版本
