### ISSUE TITLE
Creash,频繁开关几率出现

### ISSUE THREAD

**Issue by wangb123** [zzhoujay/RichText#223]
FATAL EXCEPTION: AsyncTask #3
                                                                       java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                           at android.os.AsyncTask$3.done(AsyncTask.java:325)
                                                                           at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                           at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                           at java.lang.Thread.run(Thread.java:761)
                                                                        Caused by: java.lang.IllegalArgumentException: utext_close failed: U_ILLEGAL_ARGUMENT_ERROR
                                                                           at java.util.regex.Matcher.findNextImpl(Native Method)
                                                                           at java.util.regex.Matcher.find(Matcher.java:437)
                                                                           at com.zzhoujay.markdown.parser.TagHandlerImpl.codeBlock1(TagHandlerImpl.java:733)
                                                                           at com.zzhoujay.markdown.MarkDownParser.parse(MarkDownParser.java:103)
                                                                           at com.zzhoujay.markdown.MarkDownParser.parse(MarkDownParser.java:50)
                                                                           at com.zzhoujay.markdown.MarkDown.fromMarkdown(MarkDown.java:30)
                                                                           at com.zzhoujay.richtext.parser.Markdown2SpannedParser.parse(Markdown2SpannedParser.java:22)
                                                                           at com.zzhoujay.richtext.RichText.parseRichText(RichText.java:253)
                                                                           at com.zzhoujay.richtext.RichText.generateRichText(RichText.java:240)
                                                                           at com.zzhoujay.richtext.RichText.access$100(RichText.java:37)
                                                                           at com.zzhoujay.richtext.RichText$ParseAsyncTask.doInBackground(RichText.java:183)
                                                                           at com.zzhoujay.richtext.RichText$ParseAsyncTask.doInBackground(RichText.java:167)
                                                                           at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                           at java.lang.Thread.run(Thread.java:761)

**Comment by zzhoujay** [comment]
出问题的源文本能发一下吗
