### ISSUE TITLE
多次快速调用ConcurrentModificationException

### ISSUE THREAD

**Issue by shanghongshen001** [zzhoujay/RichText#226]
`java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:318)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
	at java.util.HashMap$KeyIterator. 	(HashMap.java:885)
	at com.zzhoujay.richtext.ig.DefaultImageGetter.checkTarget(DefaultImageGetter.java:59)
	at com.zzhoujay.richtext.ig.DefaultImageGetter.getDrawable(DefaultImageGetter.java:71)
	at com.zzhoujay.richtext.RichText.getDrawable(RichText.java:374)
	at com.zzhoujay.richtext.parser.CachedSpannedParser.handleImage(CachedSpannedParser.java:120)
	at com.zzhoujay.richtext.parser.CachedSpannedParser.parse(CachedSpannedParser.java:34)
	at com.zzhoujay.richtext.RichText.generateRichText(RichText.java:244)
	at com.zzhoujay.richtext.RichText.access$100(RichText.java:37)
	at com.zzhoujay.richtext.RichText$ParseAsyncTask.doInBackground(RichText.java:183)
	at com.zzhoujay.richtext.RichText$ParseAsyncTask.doInBackground(RichText.java:167)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more`

**Comment by shanghongshen001** [comment]
` private void checkTarget(TextView textView) {
        synchronized (DefaultImageGetter.class) {
            //noinspection unchecked
            HashSet<Cancelable> cs = (HashSet<Cancelable>) textView.getTag(TASK_TAG);
            if (cs != null) {
                if (cs == tasks) {
                    return;
                }
                for (Cancelable c : cs) {
                    c.cancel();
                }
                cs.clear();
            }
            textView.setTag(TASK_TAG, tasks);
        }
    }`


出错的应该是这段代码   原因应该是多次初始化   导致多个cancel同时工作。

**Comment by zzhoujay** [comment]
试试3.0.4版本
