### ISSUE TITLE
经常出现这个问题导致崩溃，请问怎么解决

### ISSUE THREAD

**Issue by 1119093254** [zzhoujay/RichText#231]
FATAL EXCEPTION: main
                                                                    Process: com.siao.dailyhome, PID: 16284
                                                                    java.util.ConcurrentModificationException
                                                                        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
                                                                        at java.util.HashMap$KeyIterator.next(HashMap.java:885)
                                                                        at com.zzhoujay.richtext.ig.DefaultImageGetter.checkTarget(DefaultImageGetter.java:72)
                                                                        at com.zzhoujay.richtext.ig.DefaultImageGetter.getDrawable(DefaultImageGetter.java:143)
                                                                        at com.zzhoujay.richtext.RichText.getDrawable(RichText.java:336)
                                                                        at com.zzhoujay.richtext.parser.CachedSpannedParser.handleImage(CachedSpannedParser.java:120)
                                                                        at com.zzhoujay.richtext.parser.CachedSpannedParser.parse(CachedSpannedParser.java:34)
                                                                        at com.zzhoujay.richtext.RichText.generateRichText(RichText.java:180)
                                                                        at com.zzhoujay.richtext.RichText.access$000(RichText.java:37)
                                                                        at com.zzhoujay.richtext.RichText$1.run(RichText.java:147)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by zzhoujay** [comment]
哪个版本？3.0.4版本吗？

**Comment by 1119093254** [comment]
不是  2.5版本

**Comment by zzhoujay** [comment]
那试试3.0.4版本，这个版本应该解决了这个问题
