### ISSUE TITLE
最新版本不能正常加载图片，2.5.4报下面的错

### ISSUE THREAD

**Issue by QinleiChen** [zzhoujay/RichText#321]
05-06 15:32:48.180 9794-9952/com.raine.app.geekbang E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
    Process: com.raine.app.geekbang, PID: 9794
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
        at java.util.regex.Matcher.reset(Matcher.java:1045)
        at java.util.regex.Matcher.<init>(Matcher.java:174)
        at java.util.regex.Pattern.matcher(Pattern.java:1006)
        at com.zzhoujay.richtext.RichText.analyzeImages(RichText.java:251)
        at com.zzhoujay.richtext.RichText.generateRichText(RichText.java:209)
        at com.zzhoujay.richtext.RichText.access$100(RichText.java:39)
        at com.zzhoujay.richtext.RichText$2.doInBackground(RichText.java:168)
        at com.zzhoujay.richtext.RichText$2.doInBackground(RichText.java:156)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by QinleiChen** [comment]
已经解决了，是我自己传了null的参数
