### ISSUE TITLE
An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by xiaoli-style** [zzhoujay/RichText#332]
使用的是目前最新版3.0.8，我看issue里面也有几个人碰到这个问题了，都是老版本碰到的，目前新版本还没有修复这个问题吗？报错日志就是下面这些，没有具体定位到我项目的出错行，所以我也找不到哪里有问题了。

java.lang.RuntimeException: An error occured while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:300)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
    at java.util.regex.Matcher.reset(Matcher.java:177)
    at java.util.regex.Matcher.<init>(Matcher.java:90)
    at java.util.regex.Pattern.matcher(Pattern.java:297)
    at com.zzhoujay.richtext.RichText.analyzeImages(RichText.java:279)
    at com.zzhoujay.richtext.RichText.generateRichText(RichText.java:238)
    at com.zzhoujay.richtext.RichText$ParseAsyncTask.onPostExecute(RichText.java:189)
    at com.zzhoujay.richtext.RichText$ParseAsyncTask.doInBackground(RichText.java:173)
    at android.os.AsyncTask$2.call(AsyncTask.java:288)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    ... 4 more
java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
    at java.util.regex.Matcher.reset(Matcher.java:177)
    at java.util.regex.Matcher.<init>(Matcher.java:90)
    at java.util.regex.Pattern.matcher(Pattern.java:297)
    at com.zzhoujay.richtext.RichText.analyzeImages(RichText.java:279)
    at com.zzhoujay.richtext.RichText.generateRichText(RichText.java:238)
    at com.zzhoujay.richtext.RichText$ParseAsyncTask.onPostExecute(RichText.java:189)
    at com.zzhoujay.richtext.RichText$ParseAsyncTask.doInBackground(RichText.java:173)
    at android.os.AsyncTask$2.call(AsyncTask.java:288)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)

**Comment by yancy2430** [comment]
传入的HTML数据为空

**Comment by weixiao666** [comment]
我发现这个问题，就是在传入HTML数据的时候要先判空，try catch不能捕获异常，不知道什么原因
