### ISSUE TITLE
图片不能显示出来

### ISSUE THREAD

**Issue by t2314862168** [zzhoujay/RichText#341]
```java
 https://pco-member-imgs.oss-cn-qingdao.aliyuncs.com/images/f3c2bd84-7a9f-743d-5fee-e46b4746f36a/notification/20190918/5d81e31bb44b9.png
```
```java
 http://customer.pcostar.net/_nuxt/img/73c5d4d.png
```
大佬好，我现在测试http和https格式的图片都不能显示 ,使用的是最新的版本com.zzhoujay.richtext:richtext:3.0.8
翻了issue，试过使用OkHttpImageDownloader也不行，下面是设置代码
```java
RichText.fromHtml(text)
                .imageDownloader(new OkHttpImageDownloader())
                .into(tv_content);
```

下面是相关日志
```java
 at java.io.BufferedInputStream.streamClosed(BufferedInputStream.java:125)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
        at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:639)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:615)
09-18 17:18:54.078 27563-566/com.tangxb.killdebug.operater W/System.err:     at com.zzhoujay.richtext.ig.SourceDecode$3.decodeSize(SourceDecode.java:82)
        at com.zzhoujay.richtext.ig.SourceDecode$3.decodeSize(SourceDecode.java:67)
        at com.zzhoujay.richtext.ig.AbstractImageLoader.getDimensions(AbstractImageLoader.java:194)
        at com.zzhoujay.richtext.ig.AbstractImageLoader.doLoadImage(AbstractImageLoader.java:219)
        at com.zzhoujay.richtext.ig.CallbackImageLoader.onImageDownloadFinish(CallbackImageLoader.java:35)
        at com.zzhoujay.richtext.ig.ImageDownloaderManager$Task.run(ImageDownloaderManager.java:148)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
09-18 17:18:54.079 27563-566/com.tangxb.killdebug.operater D/skia: ---- read threw an exception
    --- SkImageDecoder::Factory returned null
09-18 17:18:54.079 27563-566/com.tangxb.killdebug.operater I/RichText: AbstractImageLoader --> onSizeReady > width = -1 , height = -1 , https://pco-member-imgs.oss-cn-qingdao.aliyuncs.com/images/f3c2bd84-7a9f-743d-5fee-e46b4746f36a/notification/20190918/5d81e31bb44b9.png
09-18 17:18:54.079 27563-566/com.tangxb.killdebug.operater W/System.err: java.io.IOException: BufferedInputStream is closed
09-18 17:18:54.080 27563-566/com.tangxb.killdebug.operater W/System.err:     at java.io.BufferedInputStream.streamClosed(BufferedInputStream.java:125)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
        at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:639)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:615)
        at com.zzhoujay.richtext.ig.SourceDecode$3.decodeAsBitmap(SourceDecode.java:103)
        at com.zzhoujay.richtext.ig.SourceDecode$3.decodeAsBitmap(SourceDecode.java:67)
        at com.zzhoujay.richtext.ig.SourceDecode.decode(SourceDecode.java:130)
        at com.zzhoujay.richtext.ig.AbstractImageLoader.doLoadImage(AbstractImageLoader.java:222)
        at com.zzhoujay.richtext.ig.CallbackImageLoader.onImageDownloadFinish(CallbackImageLoader.java:35)
        at com.zzhoujay.richtext.ig.ImageDownloaderManager$Task.run(ImageDownloaderManager.java:148)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
09-18 17:18:54.081 27563-566/com.tangxb.killdebug.operater W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
09-18 17:18:54.081 27563-566/com.tangxb.killdebug.operater D/skia: ---- read threw an exception
    --- SkImageDecoder::Factory returned null
09-18 17:18:54.081 27563-566/com.tangxb.killdebug.operater W/System.err: com.zzhoujay.richtext.exceptions.ImageWrapperMultiSourceException: GifDrawable和Bitmap有且只有一个为null
        at com.zzhoujay.richtext.ig.ImageWrapper.<init>(ImageWrapper.java:28)
        at com.zzhoujay.richtext.ig.ImageWrapper.createAsBitmap(ImageWrapper.java:86)
        at com.zzhoujay.richtext.ig.SourceDecode$3.decodeAsBitmap(SourceDecode.java:111)
09-18 17:18:54.082 27563-566/com.tangxb.killdebug.operater W/System.err:     at com.zzhoujay.richtext.ig.SourceDecode$3.decodeAsBitmap(SourceDecode.java:67)
09-18 17:18:54.089 27563-566/com.tangxb.killdebug.operater W/System.err:     at com.zzhoujay.richtext.ig.SourceDecode.decode(SourceDecode.java:130)
        at com.zzhoujay.richtext.ig.AbstractImageLoader.doLoadImage(AbstractImageLoader.java:222)
        at com.zzhoujay.richtext.ig.CallbackImageLoader.onImageDownloadFinish(CallbackImageLoader.java:35)
        at com.zzhoujay.richtext.ig.ImageDownloaderManager$Task.run(ImageDownloaderManager.java:148)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-18 17:18:54.090 27563-566/com.tangxb.killdebug.operater W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
09-18 17:18:55.732 942-942/? I/MSM-irqbalance: Decided to move IRQ65 from CPU2 to CPU3
09-18 17:18:56.115 4702-4702/? D/wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
```
求大佬指教下 @zzhoujay

**Comment by t2314862168** [comment]
多加一个依赖之后可以了
```java
   api 'com.zzhoujay.richtext:richtext:3.0.8'
    api 'com.zzhoujay:html:1.0.2'
```

加载代码:
```java
 RichText.initCacheDir(mActivity);
        RichText.debugMode = true;
        RichText.fromHtml(text)
                .autoFix(false)
                .fix(new ImageFixCallback() {
                    @Override
                    public void onInit(ImageHolder holder) {

                    }

                    @Override
                    public void onLoading(ImageHolder holder) {

                    }

                    @Override
                    public void onSizeReady(ImageHolder holder, int imageWidth, int imageHeight, ImageHolder.SizeHolder sizeHolder) {
                        int screenWidth = ScreenUtils.getScreenWidth(mActivity);
                        float ratio = screenWidth / imageWidth * 1f;
                        int loadImageWidth = imageWidth;
                        int loadImageHeight = imageHeight;
                        if (ratio < 1f) {
                            loadImageWidth = screenWidth;
                            loadImageHeight = (int) (imageHeight * ratio);
                        }
                        sizeHolder.setSize(loadImageWidth, loadImageHeight);
                    }

                    @Override
                    public void onImageReady(ImageHolder holder, int width, int height) {
                        System.out.println();
                    }

                    @Override
                    public void onFailure(ImageHolder holder, Exception e) {

                    }
                })
                .cache(CacheType.none)
                .into(tv_content);
```
