### ISSUE TITLE
当加载图片缓慢的时候关闭activity出现异常

### ISSUE THREAD

**Issue by dingyong666** [zzhoujay/RichText#47]
t E/AndroidRuntime: FATAL EXCEPTION: main
                                                          java.lang.NullPointerException
                                                              at com.zzhoujay.richtext.RichText$ImageTargetGif.recycle(RichText.java:367)
                                                              at com.zzhoujay.richtext.RichText.recycleTarget(RichText.java:172)
                                                              at com.zzhoujay.richtext.RichText.access$1100(RichText.java:57)
                                                              at com.zzhoujay.richtext.RichText$ImageTargetGif.onViewDetachedFromWindow(RichText.java:407)
                                                              at android.view.View.dispatchDetachedFromWindow(View.java:11983)
                                                              at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2530)
                                                              at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2530)
                                                              at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2530)

**Comment by zzhoujay** [comment]
你用的是哪个版本?

**Comment by dingyong666** [comment]
用的 最新2.0.x 的 ，这个异常不是百分百出现，出现几率大概 百分之40几率，感觉不像是网络缓慢出现的，像是缓冲的问题

**Comment by dingyong666** [comment]
用的是最新版，加载 gif 时不时会出问题

**Comment by zzhoujay** [comment]
最新版指的是具体哪个版本?你不告诉我具体的版本号我没法定位

**Comment by dingyong666** [comment]
com.zzhoujay.richtext:richtext:2.0.12

**Comment by zzhoujay** [comment]
你有没有能够准确触发这个bug的方法?我这边试很多次都没有出问题,或者能不能把你测试的数据发一下
