### ISSUE TITLE
出错了，是不是我传入的字符串有问题啊？

### ISSUE THREAD

**Issue by focus2846** [zzhoujay/RichText#53]
java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
                                                                               at java.util.regex.Matcher.reset(Matcher.java:177)
                                                                               at com.zzhoujay.richtext.ext.Base64.decode(Base64.java:102)
                                                                               at com.zzhoujay.richtext.RichText$4.getDrawable(RichText.java:491)
                                                                               at android.text.HtmlToSpannedConverter.startImg(Html.java:634)
                                                                               at android.text.HtmlToSpannedConverter.handleStartTag(Html.java:520)
                                                                               at android.text.HtmlToSpannedConverter.startElement(Html.java:761)
                                                                               at org.ccil.cowan.tagsoup.Parser.push(Parser.java:794)
                                                                               at org.ccil.cowan.tagsoup.Parser.rectify(Parser.java:1061)
                                                                               at org.ccil.cowan.tagsoup.Parser.stagc(Parser.java:1016)
                                                                               at org.ccil.cowan.tagsoup.HTMLScanner.scan(HTMLScanner.java:624)
                                                                               at org.ccil.cowan.tagsoup.Parser.parse(Parser.java:449)
                                                                               at android.text.HtmlToSpannedConverter.convert(Html.java:442)
                                                                               at android.text.Html.fromHtml(Html.java:136)
                                                                               at com.zzhoujay.richtext.parser.Html2SpannedParser.parse(Html2SpannedParser.java:19)
                                                                               at com.zzhoujay.richtext.RichText.generateRichText(RichText.java:205)
                                                                               at com.zzhoujay.richtext.RichText.access$200(RichText.java:59)
                                                                               at com.zzhoujay.richtext.RichText$1.run(RichText.java:151)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:135)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by focus2846** [comment]
[richtext.txt](https://github.com/zzhoujay/RichText/files/517366/richtext.txt)

**Comment by zzhoujay** [comment]
感谢反馈，我会尽快处理的

**Comment by zzhoujay** [comment]
你给的文本有格式有问题，img标签缺少src属性
