### ISSUE TITLE
是否提供取消任务接口

### ISSUE THREAD

**Issue by eyyoung** [zzhoujay/RichText#54]
是否提供取消任务接口？
在Activity销毁时没有取消任务容易导致内存泄露和触发Glide错误。

```
java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
    at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:134)
    at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:102)
    at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:87)
    at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:91)
    at com.bumptech.glide.Glide.with(Glide.java:629)
    at com.zzhoujay.richtext.RichText$4.getDrawable(RichText.java:495)
```

**Comment by zzhoujay** [comment]
感谢反馈，我会尽快加入的，完成后会通知你的

**Comment by zzhoujay** [comment]
在`2.0.14`版本中任务会随TextView移除而结束，或者手动调用cancel方法取消

**Comment by eyyoung** [comment]
不能依赖于onViewDetachedFromWindow来取消任务，该生命周期对于RecyclerView中的子View存在周期紊乱问题，如果使用RichText加载的控件在RecyclerView中，将导致RichText提前取消Glide任务而无法显示图片。建议取消自动调用该方法，或者往上查找父级RecyclerView使用addOnChildAttachStateChangeListener

**Comment by zzhoujay** [comment]
确实，感谢建议，已在`2.1.0`版本中去掉了上述的做法，改为手动调用`clear`方法。

**Comment by eyyoung** [comment]
在AsyncImageGetter中使用下面的代码判断Activity是否被destroyed，
```
if(textView.getContext() instanceof Activity){
        if (((Activity) textView.getContext()).isDestroyed()) {
               return new ColorDrawable(Color.TRANSPARENT);
        }
}
```

上述代码的textView如果在AppCompatActivity中，textView的Context将不会是Activity的子类，实际上会在inflater期context会被替换成TintContextWrapper而导致上面的代码失效，需要从wrapper中提取出来真是的Activity作为判断。

```
Activity activityFromContextWrapper = getActivityFromContextWrapper(textView.getContext());
if (activityFromContextWrapper != null) {
        if (activityFromContextWrapper.isDestroyed()) {
            return new ColorDrawable(Color.TRANSPARENT);
        }
} else {
       return new ColorDrawable(Color.TRANSPARENT);
}
if (TextUtils.isEmpty(source)) {
      return new ColorDrawable(Color.TRANSPARENT);
}
```

**Comment by zzhoujay** [comment]
感谢提醒，已经在`2.1.2`版本修复了
