### ISSUE TITLE
出现 java.util.EmptyStackException错误

### ISSUE THREAD

**Issue by zyascend** [zzhoujay/RichText#59]
java.util.EmptyStackException
                                                                          at java.util.Stack.pop(Stack.java:73)
                                                                          at com.zzhoujay.richtext.ext.HtmlTagHandler.handleTag(HtmlTagHandler.java:43)
                                                                          at android.text.HtmlToSpannedConverter.handleEndTag(Html.java:574)
                                                                          at android.text.HtmlToSpannedConverter.endElement(Html.java:768)
                                                                          at org.ccil.cowan.tagsoup.Parser.pop(Parser.java:736)
                                                                          at org.ccil.cowan.tagsoup.Parser.etag_basic(Parser.java:706)
                                                                          at org.ccil.cowan.tagsoup.Parser.etag(Parser.java:644)
                                                                          at org.ccil.cowan.tagsoup.HTMLScanner.scan(HTMLScanner.java:493)
                                                                          at org.ccil.cowan.tagsoup.Parser.parse(Parser.java:449)
                                                                          at android.text.HtmlToSpannedConverter.convert(Html.java:445)
                                                                          at android.text.Html.fromHtml(Html.java:139)
                                                                          at com.zzhoujay.richtext.parser.Html2SpannedParser.parse(Html2SpannedParser.java:19)
                                                                          at com.zzhoujay.richtext.RichText.generateRichText(RichText.java:212)
                                                                          at com.zzhoujay.richtext.RichText.access$200(RichText.java:61)
                                                                          at com.zzhoujay.richtext.RichText$1.run(RichText.java:158)
                                                                          at android.os.Handler.handleCallback(Handler.java:733)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by zzhoujay** [comment]
这个问题已经发现了，是这个版本代码疏忽产生的BUG，可以先回退到上个上个版本，或是等待下个版本修复

**Comment by zyascend** [comment]
好的，知道了，非常感谢。

**Comment by zzhoujay** [comment]
应该的

**Comment by zyascend** [comment]
对了，上个版本的版本号是多少呢

**Comment by zzhoujay** [comment]
2.0.14，就是小版本号减一

**Comment by zyascend** [comment]
╰(￣▽￣)╮完美运行，再次感谢。

**Comment by Xiemarc** [comment]
你好，数据是
设集合<img src="http://182.92.3.219/Uploads/word/2016/0810/57aa82d276f31730450.files/image002.png" style="vertical-align:middle;" />,<img src="http://182.92.3.219/Uploads/word/2016/0810/57aa82d276f31730450.files/image004.png" style="vertical-align:middle;" />

**Comment by Xiemarc** [comment]
width和height都是-1，没有拿到。

**Comment by zzhoujay** [comment]
@Xiemarc 
这个在wiki里有提到过[wiki](https://github.com/zzhoujay/RichText/wiki/Manual-fix)

onFix方法会先后调用两次，一次加载前（是从img标签中获取的），一次加载后，通过`imageReady`这个flag来区分，如果img标签中宽高属性没有的话，第一次onFix方法将获取不到width和height，可以在加载后第二次调用时获取到，但是如果图片加载失败，第二次将不会调用。

**Comment by zzhoujay** [comment]
@zyascend 在`2.1.0`版本中已修复

**Comment by zyascend** [comment]
@zzhoujay 知道了，谢谢提醒
