### ISSUE TITLE
Cannot draw recycled bitmaps 

### ISSUE THREAD

**Issue by stevefat** [zzhoujay/RichText#74]
```
java.lang.IllegalArgumentException: Cannot draw recycled bitmaps
  at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:789)
  at android.view.GLES20RecordingCanvas.drawBitmap(GLES20RecordingCanvas.java:118)
  at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:393)
  at com.zzhoujay.richtext.drawable.URLDrawable.draw(URLDrawable.java:22)
  at android.text.style.DynamicDrawableSpan.draw(DynamicDrawableSpan.java:107)
```

**Comment by zzhoujay** [comment]
OK，会在下个版本中修复这个问题，到时候会通知你

**Comment by zzhoujay** [comment]
问题已经在`2.2.0`版本中修复
