### ISSUE TITLE
Canvas: trying to use a recycled bitmap android.graphics.Bitmap@42b49cf0

### ISSUE THREAD

**Issue by chenwulue** [zzhoujay/RichText#77]
`java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@42b49cf0
                                         at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1109)
                                         at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:848)
                                         at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:490)
                                         at com.zzhoujay.richtext.drawable.URLDrawable.draw(URLDrawable.java:22)
                                         at android.text.style.DynamicDrawableSpan.draw(DynamicDrawableSpan.java:107)
                                         at android.text.TextLine.handleReplacement(TextLine.java:863)
                                         at android.text.TextLine.handleRun(TextLine.java:947)
                                         at android.text.TextLine.drawRun(TextLine.java:396)
                                         at android.text.TextLine.draw(TextLine.java:194)
                                         at android.text.Layout.drawText(Layout.java:358)
                                         at android.widget.Editor.drawHardwareAccelerated(Editor.java:1537)
                                         at android.widget.Editor.onDraw(Editor.java:1442)
                                         at android.widget.TextView.onDraw(TextView.java:5452)
                                         at android.view.View.draw(View.java:15359)
                                         at android.view.View.getDisplayList(View.java:14127)
                                         at android.view.View.getDisplayList(View.java:14174)
                                         at android.view.View.draw(View.java:15061)
                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3304)
                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3122)
                                         at android.view.View.getDisplayList(View.java:14119)
                                         at android.view.View.getDisplayList(View.java:14174)
                                         at android.view.View.draw(View.java:15061)
                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3304)
                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3122)
                                         at android.view.View.getDisplayList(View.java:14119)
                                         at android.view.View.getDisplayList(View.java:14174)
                                         at android.view.View.draw(View.java:15061)
                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3304)
                                         at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4243)
                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3122)
                                         at android.view.View.draw(View.java:15370)
                                         at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3652)
                                         at android.view.View.getDisplayList(View.java:14127)
                                         at android.view.View.getDisplayList(View.java:14174)
                                         at android.view.View.draw(View.java:15061)
                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3304)
                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3122)
                                         at android.view.View.getDisplayList(View.java:14119)
                                         at android.view.View.getDisplayList(View.java:14174)
                                         at android.view.View.draw(View.java:15061)
                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3304)
                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3142)
                                         at android.view.View.draw(View.java:15370)
                                         at android.view.View.getDisplayList(View.java:14127)
                                         at android.view.View.getDisplayList(View.java:14174)
                                         at android.view.View.draw(View.java:15061)
                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3304)
                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3122)
                                         at android.view.View.draw(View.java:15370)
                                         at android.view.View.getDisplayList(View.java:14127)
                                         at android.view.View.getDisplayList(View.java:14174)
                                         at android.view.View.draw(View.java:15061)
                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3304)
                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3122)
                                         at android.view.View.getDisplayList(View.java:14119)
                                         at android.view.View.getDisplayList(View.java:14174)
                                         at android.view.View.draw(View.java:15061)
                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3304)
                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3122)
                                         at android.view.View.getDisplayList(View.java:14119)
                                         at android.view.View.getDisplayList(View.java:14174)
                                         at android.view.View.draw(View.java:15061)
                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3304)
                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3122)
                                         at android.view.View.getDisplayList(View.java:14119)
                                         at android.view.View.getDisplayList(View.java:14174)
                                         at android.view.View.draw(View.java:15061)
                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3304)
                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3122)
                                         at android.view.View.draw(View.java:15370)
                                     	at android.widget`

**Comment by chenwulue** [comment]
升级2.2.0好像没问题了。。

**Comment by zzhoujay** [comment]
恩，`2.2.0`修复了这个bug
