### ISSUE TITLE
err: Height must be positive number or 0.

### ISSUE THREAD

**Issue by qq137712630** [zzhoujay/RichText#8]
你好，我在使用例子时，下面的html时报错了： Height must be positive number or 0.
请问需要如何修改？

代码如下：

    private static final String TEXT_HTML ="<img src=\"http://www.chn-zj.com/upload/image/Wc2cw3CZ.png\" alt=\"深圳朗锐智建有限公司\" width=\"288\" height=\"48\"/><Br/><div id=\"sta_content\"> \n"+
        " <p style=\"text-indent:2em;\"> <span style=\"font-size:14px;\"><span style=\"line-height:2;\">公司简介：</span><br> <span style=\"line-height:2;\"> &nbsp; &nbsp; &nbsp; &nbsp; 深圳朗锐智建科技有限公司，即</span><span style=\"line-height:2;\">智能建筑物联网综合方案运营商。</span></span> </p> \n"+
        " <p style=\"text-indent:2em;\"> <span style=\"font-size:14px;\"></span><span style=\"font-size:14px;line-height:2;\"> &nbsp; </span><span style=\"font-size:14px;line-height:2;\">专注智慧建筑，以物联网为骨干，以智能终端为神经元，以云平台为决策思维，实现幸福城市建</span><span style=\"font-size:14px;line-height:2;\">筑智慧化，提升建筑生态环境品质，培育具生命的活体建筑。</span> </p> \n"+
        " <p style=\"text-indent:2em;\"> <span style=\"font-size:14px;\"><span style=\"line-height:2;\">&nbsp;&nbsp;</span><span><span style=\"line-height:2;\">公司目前自主研发多项</span></span></span><span style=\"font-size:14px;line-height:28px;\">产品</span><span style=\"font-size:14px;text-indent:2em;line-height:2;\">，包括楼宇自动化系统、BMS楼宇管理系统、大型公建能耗监管平台、多功能能耗数据采集器、智能控制器等。公司以筑造智能科技平台，在建筑物联网行业中成为行业领军企业</span><span style=\"font-size:14px;text-indent:2em;line-height:2;\">。</span> </p> \n"+
        "</div>";

    text.setRichText(TEXT_HTML);

 报错：

 错误位置：
RichText.java:265行

     if (holder.width != -1 && holder.height != -1) {
        load.resize(holder.width, holder.height);
    }

	java.lang.RuntimeException: Unable to start activity ComponentInfo{zhou.demo/zhou.demo.MainActivity}: java.lang.IllegalArgumentException: Height must be positive number or 0.
	   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2581)
	   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2656)
	   at android.app.ActivityThread.access$800(ActivityThread.java:178)
	   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1512)
	   at android.os.Handler.dispatchMessage(Handler.java:111)
	   at android.os.Looper.loop(Looper.java:194)
	   at android.app.ActivityThread.main(ActivityThread.java:5691)
	   at java.lang.reflect.Method.invoke(Native Method)
	   at java.lang.reflect.Method.invoke(Method.java:372)
	   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
	Caused by: java.lang.IllegalArgumentException: Height must be positive number or 0.
	   at com.squareup.picasso.Request$Builder.resize(Request.java:302)
	   at com.squareup.picasso.RequestCreator.resize(RequestCreator.java:219)
	   at zhou.widget.RichText$2.getDrawable(RichText.java:265)
	   at android.text.HtmlToSpannedConverter.startImg(Html.java:634)
	   at android.text.HtmlToSpannedConverter.handleStartTag(Html.java:520)
	   at android.text.HtmlToSpannedConverter.startElement(Html.java:761)
	   at org.ccil.cowan.tagsoup.Parser.push(Parser.java:794)
	   at org.ccil.cowan.tagsoup.Parser.rectify(Parser.java:1061)
	   at org.ccil.cowan.tagsoup.Parser.stage(Parser.java:1026)
	   at org.ccil.cowan.tagsoup.HTMLScanner.scan(HTMLScanner.java:632)
	   at org.ccil.cowan.tagsoup.Parser.parse(Parser.java:449)
	   at android.text.HtmlToSpannedConverter.convert(Html.java:442)
	   at android.text.Html.fromHtml(Html.java:136)
	   at zhou.widget.RichText.setRichText(RichText.java:102)
	   at zhou.demo.MainActivity.onCreate(MainActivity.java:68)
	   at android.app.Activity.performCreate(Activity.java:6142)
	   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115)
	   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2528)
	   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2656) 
	   at android.app.ActivityThread.access$800(ActivityThread.java:178) 
	   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1512) 
	   at android.os.Handler.dispatchMessage(Handler.java:111) 
	   at android.os.Looper.loop(Looper.java:194) 
	   at android.app.ActivityThread.main(ActivityThread.java:5691) 
	   at java.lang.reflect.Method.invoke(Native Method) 
	   at java.lang.reflect.Method.invoke(Method.java:372) 
	   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
	   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by qq137712630** [comment]
这样把修改图片的方法给去了就可以正常显示：	   

	    @Override
	    protected void onCreate(Bundle savedInstanceState) {
	        super.onCreate(savedInstanceState);
	        setContentView(R.layout.activity_main);

	        RichText text = (RichText) findViewById(R.id.text);


	        text.setOnImageClickListener(new RichText.OnImageClickListener() {
	            @Override
	            public void imageClicked(List<String> imageUrls, int position) {
	                Toast.makeText(getApplicationContext(), imageUrls.get(position), Toast.LENGTH_SHORT).show();
	            }
	        });

	        text.setOnURLClickListener(new RichText.OnURLClickListener() {
	            @Override
	            public boolean urlClicked(String url) {
	                Toast.makeText(getApplicationContext(), url, Toast.LENGTH_SHORT).show();
	                return true;
	            }
	        });
	//
	//        text.setImageFixListener(new RichText.ImageFixListener() {
	//            @Override
	//            public void onFix(RichText.ImageHolder holder) {
	//                if (holder.getWidth() > 100 || holder.getHeight() > 100) {
	//                    int width = getScreenWidth(getApplicationContext());
	//                    int height = (int) (holder.getHeight() * 1f * width / holder.getWidth()) - 300;
	//                    holder.setWidth(width);
	//                    holder.setHeight(height);
	//                    holder.setScaleType(RichText.ImageHolder.CENTER_INSIDE);
	//                }
	//            }
	//        });

	        text.setRichText(TEXT_HTML);

	    }
